"""Paths and constants the framework needs, all in one place.

Override any of these via env vars before invoking pytest — useful
in CI where paths differ from a dev box, or when running against a
non-default vhost config.
"""

import os

# xdist worker isolation.
#
# Under -n the workers must not share one Apache: config_override
# rewrites a vhost file and reloads, so concurrent workers interleave
# edits into invalid config. Measured before this existed: two overrides
# collided into mode='monitor', httpd refused to start, and 177 tests
# failed for that reason rather than on their own merits.
#
# Each worker therefore addresses its own server instance, generated by
# tests/setup/make-instance.sh and run as httpd-bstest@<n>. Ports, logs
# and the BotShield state file are all per-instance.
#
# The per-worker values deliberately take precedence over the BS_*
# environment variables. bstest.env exports BS_BASE and friends pointing
# at the single instance, and honouring those under xdist would send
# every worker back to one server -- which is the exact failure this
# exists to prevent. Outside xdist the env vars win as before, so a
# plain `pytest` run is unchanged.
_WORKER = os.environ.get("PYTEST_XDIST_WORKER", "")
WORKER_N = (int(_WORKER[2:])
            if _WORKER.startswith("gw") and _WORKER[2:].isdigit() else None)
_PAR = WORKER_N is not None


# Which Apache is this?
#
# One place decides, because the harness previously did not have one: it
# shelled out to `httpd`, the RHEL binary name, while defaulting its
# config paths to /etc/apache2, the Debian layout. That combination is
# wrong on both platforms, and it failed differently on each -- on RHEL
# the paths were wrong unless you remembered to source bstest.env, and
# on Ubuntu CI the binary did not exist at all, so every config-parse
# test failed with "httpd: command not found" and had done for months.
#
# Detection is by binary, not by /etc/os-release, because what matters
# is the Apache that is installed rather than the distribution name.
def _detect_platform():
    if os.environ.get("BS_PLATFORM"):
        return os.environ["BS_PLATFORM"]
    if os.path.exists("/usr/sbin/httpd"):
        return "rhel"
    if os.path.exists("/usr/sbin/apache2"):
        return "debian"
    raise RuntimeError(
        "cannot find an Apache: looked for /usr/sbin/httpd and "
        "/usr/sbin/apache2. Set BS_PLATFORM=rhel|debian to override."
    )


PLATFORM = _detect_platform()
_RHEL = PLATFORM == "rhel"

# The binary the harness invokes for `-t` config checks and the policy
# dump.
#
# Debian gets apache2ctl rather than apache2, and that is not a
# stylistic choice: apache2.conf refers to ${APACHE_RUN_DIR} and friends,
# which are defined in /etc/apache2/envvars and sourced by the ctl
# wrapper. Invoking apache2 directly makes every config test fail with
# AH00111 "Config variable is not defined", which is what CI was doing.
HTTPD_BIN = os.environ.get("BS_HTTPD_BIN",
                           "httpd" if _RHEL else "apache2ctl")


# How the instance is started and stopped.
#
# systemd where there is one, which is every real box and this project's
# per-worker instances. Not in a container: GitHub's `container:` jobs
# have no init, so `systemctl` is not merely absent, it cannot work. An
# httpd knows how to signal itself, and `httpd -f <conf> -k graceful` is
# both simpler and more direct than asking an init system to pass the
# message along. Detected rather than configured, with BS_SERVICE_MODE
# to force it.
def _detect_service_mode():
    if os.environ.get("BS_SERVICE_MODE"):
        return os.environ["BS_SERVICE_MODE"]
    if os.path.exists("/run/systemd/system"):
        return "systemd"
    return "direct"


SERVICE_MODE = _detect_service_mode()


def _plat(rhel_value, debian_value):
    """Pick the platform-appropriate default."""
    return rhel_value if _RHEL else debian_value


def _pick(env_key, default, worker_value):
    if _PAR:
        return worker_value
    return os.environ.get(env_key, default)


BASE_URL = _pick("BS_BASE",
                 _plat("https://localhost:8443", "https://localhost"),
                 "https://localhost:%d" % (8543 + (WORKER_N or 0)))
ERROR_LOG = _pick("BS_ERROR_LOG",
                  _plat("/var/log/httpd/bstest/botshield-dev-error.log",
                        "/var/log/apache2/botshield-dev-error.log"),
                  "/var/log/httpd/bstest/w%d/botshield-dev-error.log" % (WORKER_N or 0))
APACHE_ERROR_LOG = _pick("BS_APACHE_ERROR_LOG",
                         _plat("/var/log/httpd/bstest/error.log",
                               "/var/log/apache2/error.log"),
                         "/var/log/httpd/bstest/w%d/error.log" % (WORKER_N or 0))
DEV_VHOST_CONF = _pick("BS_DEV_VHOST_CONF",
                       _plat("/etc/httpd/bstest/dev-vhost.conf",
                             "/etc/apache2/sites-available/botshield-dev.conf"),
                       "/etc/httpd/bstest/w%d/dev-vhost.conf" % (WORKER_N or 0))
APACHE_SERVICE = _pick("BS_APACHE_SERVICE",
                       _plat("httpd-bstest", "apache2"),
                       "httpd-bstest@%d" % (WORKER_N or 0))

# The instance's own httpd.conf, for `httpd -f ... -C <directive> -t`
# config-rejection checks. These MUST NOT run against the production
# config: it loads the deployed module, so a test for a directive the
# working tree has just added would assert against the old build and
# report a parser error that says nothing about the new code.
HTTPD_CONF = _pick("BS_HTTPD_CONF",
                   _plat("/etc/httpd/bstest/httpd.conf",
                         "/etc/apache2/apache2.conf"),
                   "/etc/httpd/bstest/w%d/httpd.conf" % (WORKER_N or 0))
# The standalone decision log (BotShieldDecisionLog). Distinct from
# ERROR_LOG: decision lines appear in BOTH, but only in the error log
# with the "mod_botshield: decision " prefix that _parse_decision keys
# on. Lines the module writes straight to this file and nowhere else --
# observability-endpoint hits, for one -- are only visible here.
DECISION_LOG = _pick("BS_DECISION_LOG",
                     _plat("/var/log/httpd/bstest/botshield.log",
                           "/var/log/apache2/botshield.log"),
                     "/var/log/httpd/bstest/w%d/botshield.log" % (WORKER_N or 0))
STATE_FILE = _pick("BS_STATE_FILE",
                   _plat("/var/lib/botshield-test/state.bin",
                         "/var/lib/botshield/state.bin"),
                   "/var/lib/botshield-test/state-w%d.bin" % (WORKER_N or 0))
# The external load-state file BotShieldLoadStateFile points at. Tests
# write it and the request path reads it, so it follows the same
# per-worker split as everything else: BotShieldLoadStateFile is server
# scope and every worker runs its own httpd, so a shared path would let
# one worker's "hot" leak into another's expectation of "normal". A test
# writing the shared path while its instance reads a per-worker one just
# times out waiting for a transition that will never arrive.
LOAD_STATE_FILE = _pick("BS_LOAD_STATE_FILE",
                        "/etc/botshield/load.state.test",
                        "/etc/botshield/load.state.w%d.test" % (WORKER_N or 0))
DEFAULT_TIMEOUT = float(os.environ.get("BS_DEFAULT_TIMEOUT", "10"))
