"""Paths and constants the framework needs, all in one place.

Override any of these via env vars before invoking pytest — useful
in CI where paths differ from a dev box, or when running against a
non-default vhost config.
"""

import os

# xdist worker isolation.
#
# Under -n the workers must not share one Apache: config_override
# rewrites a vhost file and reloads, so concurrent workers interleave
# edits into invalid config. Measured before this existed: two overrides
# collided into mode='monitor', httpd refused to start, and 177 tests
# failed for that reason rather than on their own merits.
#
# Each worker therefore addresses its own server instance, generated by
# tests/setup/make-instance.sh and run as httpd-bstest@<n>. Ports, logs
# and the BotShield state file are all per-instance.
#
# The per-worker values deliberately take precedence over the BS_*
# environment variables. bstest.env exports BS_BASE and friends pointing
# at the single instance, and honouring those under xdist would send
# every worker back to one server -- which is the exact failure this
# exists to prevent. Outside xdist the env vars win as before, so a
# plain `pytest` run is unchanged.
_WORKER = os.environ.get("PYTEST_XDIST_WORKER", "")
WORKER_N = (int(_WORKER[2:])
            if _WORKER.startswith("gw") and _WORKER[2:].isdigit() else None)
_PAR = WORKER_N is not None


def _pick(env_key, default, worker_value):
    if _PAR:
        return worker_value
    return os.environ.get(env_key, default)


BASE_URL = _pick("BS_BASE", "https://localhost",
                 "https://localhost:%d" % (8543 + (WORKER_N or 0)))
ERROR_LOG = _pick("BS_ERROR_LOG",
                  "/var/log/apache2/botshield-dev-error.log",
                  "/var/log/httpd/bstest/w%d/botshield-dev-error.log" % (WORKER_N or 0))
APACHE_ERROR_LOG = _pick("BS_APACHE_ERROR_LOG",
                         "/var/log/apache2/error.log",
                         "/var/log/httpd/bstest/w%d/error.log" % (WORKER_N or 0))
DEV_VHOST_CONF = _pick("BS_DEV_VHOST_CONF",
                       "/etc/apache2/sites-available/botshield-dev.conf",
                       "/etc/httpd/bstest/w%d/dev-vhost.conf" % (WORKER_N or 0))
APACHE_SERVICE = _pick("BS_APACHE_SERVICE", "apache2",
                       "httpd-bstest@%d" % (WORKER_N or 0))

# External load-state file the module watches. Per worker, because
# BotShieldLoadStateFile is server scope: every worker runs its own
# httpd, so a shared path would let one worker's "hot" leak into
# another's expectation of "normal" -- the same interference the
# per-worker instances exist to prevent.
LOAD_STATE_FILE = _pick("BS_LOAD_STATE_FILE",
                        "/etc/botshield/load.state.test",
                        "/etc/botshield/load.state.w%d.test" % (WORKER_N or 0))
# The instance's own httpd.conf, for `httpd -f ... -C <directive> -t`
# config-rejection checks. These MUST NOT run against the production
# config: it loads the deployed module, so a test for a directive the
# working tree has just added would assert against the old build and
# report a parser error that says nothing about the new code.
HTTPD_CONF = _pick("BS_HTTPD_CONF", "/etc/apache2/apache2.conf",
                   "/etc/httpd/bstest/w%d/httpd.conf" % (WORKER_N or 0))
STATE_FILE = _pick("BS_STATE_FILE", "/var/lib/botshield/state.bin",
                   "/var/lib/botshield-test/state-w%d.bin" % (WORKER_N or 0))
# The external load-state file BotShieldLoadStateFile points at. Tests
# write it and the request path reads it, so it has to follow the same
# per-worker split as everything else -- a test writing the shared path
# while its instance reads a per-worker one just times out waiting for a
# transition that will never arrive.
LOAD_STATE_FILE = _pick("BS_LOAD_STATE_FILE",
                        "/etc/botshield/load.state.test",
                        "/etc/botshield/load.state.w%d.test" % (WORKER_N or 0))
DEFAULT_TIMEOUT = float(os.environ.get("BS_DEFAULT_TIMEOUT", "10"))
