/* generated_bot_directory.c — auto-generated; do NOT edit by hand.
 *
 * Regenerated from vendor/bot-directory.json by
 * tools/gen-bot-directory.py. Edit the JSON or the generator,
 * then re-run via the Makefile rule. */

#include <stddef.h>   /* NULL */

#include "bot_directory.h"

const bs_known_bot_entry bs_known_bots[] = {
    { "https://www.loc.gov/programs/web-archiving/for-site-owners/", "library-of-congress-web-archiving", "ACADEMIC_RESEARCH", "ai-train" },
    { "AppleWebKit/605.1.15 (KHTML, like Gecko) Chrome/", "fake-chrome-webkit-605", "OTHER", NULL },
    { "Chrome Privacy Preserving Prefetch Proxy", "chrome-private-prefetch-proxy", "OTHER", NULL },
    { "Cloudflare Custom Hostname Verification", "cloudflare-chv", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "paloaltonetworks.com/r/1/Cortex-Xpanse", "palo-alto-xpanse", "SECURITY", NULL },
    { "CloudflareBrowserRenderingCrawler/1.0", "cloudflare-browser-rendering-crawler", "AI_CRAWLER", "ai-train" },
    { "36b1546a5700e52eb2972b3f92b314fa", "blockaid", "SECURITY", NULL },
    { "https://iframely.com/docs/about", "iframely", "PAGE_PREVIEW", "search" },
    { "Google-Structured-Data-Testing", "googledata", "MONITORING_AND_ANALYTICS", "monitor" },
    { "AfterShip Magento-2 Connector", "aftership-magento-2", "WEBHOOKS", NULL },
    { "http://easyurl.net/monitoring", "easydns", "MONITORING_AND_ANALYTICS", "monitor" },
    { "http://www.ezoic.com/bot.html", "ezoicbot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Google-Flights-Search-Spackle", "google-flights-search-spackle", "SEARCH_ENGINE_CRAWLER", "search" },
    { "InteractiveAdvertisingBureau", "adstxtcrawler", "ADVERTISING_AND_MARKETING", NULL },
    { "Clickagy Intelligence Bot v2", "clickagy", "ADVERTISING_AND_MARKETING", NULL },
    { "grafana/synthetic-monitoring", "grafana-labs", "MONITORING_AND_ANALYTICS", "monitor" },
    { "WPMU DEV Broken Link Checker", "wpmu-dev-broken-link-checker", "MONITORING_AND_ANALYTICS", "monitor" },
    { "http://www.binarycanary.com", "binarycanary", "MONITORING_AND_ANALYTICS", "monitor" },
    { "https://www.letsencrypt.org", "letsencrypt", "SECURITY", NULL },
    { "ZoteroTranslationServer/WMF", "wikimedia-zotero", "OTHER", NULL },
    { "ApifyWebsiteContentCrawler", "apify-website-content-crawler", "AI_ASSISTANT", "ai-input" },
    { "Cloudflare-Traffic-Manager", "cloudflare-traffic-manager", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "synthetic-monitoring-agent", "grafana-synthetic-monitoring-2", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Cloudflare Stream Webhook", "cloudflare-stream-webhook", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Cozi-iCalendar-FeedReader", "cozi-icalendar", "FEED_FETCHER", NULL },
    { "Google-BusinessLinkVerifi", "google-businesslinkverification", "SECURITY", NULL },
    { "LogicMonitor SiteMonitor/", "logicmonitor", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Overcast/1.0 Podcast Sync", "overcast", "FEED_FETCHER", NULL },
    { "Screaming Frog SEO Spider", "screaming-frog-seo-spider", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "agentready.cloudflare.com", "cloudflare-agent-readiness", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Honeybadger Uptime Check", "boneybadgerbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Google-Calendar-Importer", "google-calendar-importer-2", "FEED_FETCHER", NULL },
    { "GoogleAssociationService", "google-digital-asset-links", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Google-Site-Verification", "google-site-verification", "SECURITY", NULL },
    { "MediavineMetadataParser/", "mediavine-metadata-parser", "ADVERTISING_AND_MARKETING", NULL },
    { "Pocket Casts Feed Parser", "pocketcasts-feed-parser", "FEED_FETCHER", NULL },
    { "LinkCheck by Siteimprove", "siteimprove-linkcheck", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Seamus the Search Engine", "seamus-search-engine", "ACADEMIC_RESEARCH", "ai-train" },
    { "AutomatonHeadlessChrome", "automaton", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Cloudflare-Healthchecks", "cloudflare-health-checks", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "http://www.pingdom.com/", "pingdom", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Sansec Security Monitor", "sansec-security-monitor", "SECURITY", NULL },
    { "Shortwave Image Fetcher", "shortwave-image-fetcher", "PAGE_PREVIEW", "search" },
    { "Cloudflare-SSLDetector", "cloudflare-ssl-detector", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "easybill-ImportManager", "easybill-import-manager", "OTHER", NULL },
    { "Google-AdWords-Express", "google-adwords-express", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Google-Adwords-Instant", "google-adwords-instant", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Google-Display-Ads-Bot", "googledisplayads", "ADVERTISING_AND_MARKETING", NULL },
    { "google.com/feedfetcher", "googlefeedfetcher", "FEED_FETCHER", NULL },
    { "HelloworkJobPostingBot", "hellowork-bot", "OTHER", NULL },
    { "ProjectShield-UrlCheck", "project-shield-urlcheck", "SECURITY", NULL },
    { "Y!J-BRZ/YATSHA crawler", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "http://yandex.com/bots", "yandex", "SEARCH_ENGINE_CRAWLER", "search" },
    { "ArchiveTeam ArchiveBot", "archive-team-archivebot", "ARCHIVER", "search" },
    { "Slackbot-LinkExpanding", "slackbot-linkexpanding", "PAGE_PREVIEW", "search" },
    { "zhanzhang.toutiao.com", "bytedance-toutiao", "SEARCH_ENGINE_CRAWLER", "search" },
    { "CloudflareDiagnostics", "cloudflare-diagnostics", "MONITORING_AND_ANALYTICS", "monitor" },
    { "compatible; Detectify", "detectify", "SECURITY", NULL },
    { "crawler.freespoke.com", "freespoke", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Google-InspectionTool", "google-inspection-tool", "SECURITY", NULL },
    { "Google-TravelAds-Live", "google-travelads-live", "ADVERTISING_AND_MARKETING", NULL },
    { "Google-Trust-Services", "google-trust-services", "SECURITY", NULL },
    { "meta-externalfetcher/", "meta-externalfetcher", "AI_ASSISTANT", "ai-input" },
    { "scraping@nytimes\\.com", "new-york-times-newsgathering", "OTHER", NULL },
    { "productsup.io/crawler", "productsup-crawler", "ADVERTISING_AND_MARKETING", NULL },
    { "RedactusWebClassifier", "redactus-web-classifier", "SECURITY", NULL },
    { "SERankingBacklinksBot", "serankingbacklinksbot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "XY-Archive-Compliance", "xy-archive-compliance-bot", "OTHER", NULL },
    { "Y!J-BRY/YATSH crawler", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "AgentReadinessScanner", "cloudflare-agent-readiness", "MONITORING_AND_ANALYTICS", "monitor" },
    { "visionheight.com/scan", "visionheight", "SECURITY", NULL },
    { "VelenPublicWebCrawler", "velen", "OTHER", NULL },
    { "BufferLinkPreviewBot", "bufferlinkpreviewbot", "PAGE_PREVIEW", "search" },
    { "Cloudflare-AI-Search", "cloudflare-ai-search", "AI_SEARCH", "ai-input" },
    { "Cloudflare SpeedTest", "cloudflare-speedtest", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Cloudflare-Validator", "cloudflare-validator", "OTHER", NULL },
    { "netEstate NE Crawler", "datenbank", "AI_CRAWLER", "ai-train" },
    { "w4mwnpbXf3MFAbxOkJRw", "echoboxbot", "AI_CRAWLER", "ai-train" },
    { "Mediapartners-Google", "googlemedia", "ADVERTISING_AND_MARKETING", NULL },
    { "HubSpot Page Fetcher", "hubspot-page-fetcher", "PAGE_PREVIEW", "search" },
    { "search.marginalia.nu", "marginaliabot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "meta-externalads/1.1", "meta-externalads", "ADVERTISING_AND_MARKETING", NULL },
    { "compatible; proximic", "proximic", "ADVERTISING_AND_MARKETING", NULL },
    { "Rackspace Monitoring", "rackspace", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Shopify-Captain-Hook", "shopify-captain-hook", "WEBHOOKS", NULL },
    { "websitepulse checker", "websitepulse", "MONITORING_AND_ANALYTICS", "monitor" },
    { "WP Time Capsule API/", "wp-time-capsule", "WEBHOOKS", NULL },
    { "Y!J-BRJ/YATS crawler", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "twoogle498@umich.edu", "umich-eecs498", "ACADEMIC_RESEARCH", "ai-train" },
    { "Owler (ows.eu/owler)", "owler", "MONITORING_AND_ANALYTICS", "monitor" },
    { "PRTG Network Monitor", "prtg", "MONITORING_AND_ANALYTICS", "monitor" },
    { "MyEducationalCrawler", "myeducationalcrawler", "ACADEMIC_RESEARCH", "ai-train" },
    { "Arquivo-web-crawler", "arquivo", "ARCHIVER", "search" },
    { "artemis web reader/", "artemis-web-reader", "FEED_FETCHER", NULL },
    { "BoardGamePrices Bot", "boardgameprices-bot", "AGGREGATOR", NULL },
    { "CloudFlare-Prefetch", "cloudflare-prefetch", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "facebookexternalhit", "facebook", "PAGE_PREVIEW", "search" },
    { "Google-PageRenderer", "google-pagerenderer-3", "PAGE_PREVIEW", "search" },
    { "Google-PageRenderer", "google-web-snippet-2", "PAGE_PREVIEW", "search" },
    { "HubSpot-FeedFetcher", "hubspot-feed-fetcher", "FEED_FETCHER", NULL },
    { "MediaMonitoringBot/", "media-monitoring-bot", "AGGREGATOR", NULL },
    { "meta-webindexer/1.1", "meta-web-indexer", "PAGE_PREVIEW", "search" },
    { "Mollie HTTP client/", "molliebot", "WEBHOOKS", NULL },
    { "OKX-dolphin-crawler", "okx-dolphin-crawler", "SECURITY", NULL },
    { "OutsellURLValidator", "outsell-url-validator", "MONITORING_AND_ANALYTICS", "monitor" },
    { "PWABuilderHttpAgent", "pwabuilder", "OTHER", NULL },
    { "rakutenusabot-image", "rakutenusabot-image", "OTHER", NULL },
    { "seo-audit-check-bot", "seo-audit-check-bot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "SiteCheck-sitecrawl", "sitecheck-sitecrawl", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "monitor/webpagetest", "webpagetest", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Yahoo Ad monitoring", "yahooadmonitor", "ADVERTISING_AND_MARKETING", NULL },
    { "InternetMeasurement", "internet-measurement", "SECURITY", NULL },
    { "Bitbucket-Webhooks", "bitbucket", "WEBHOOKS", NULL },
    { "BrightEdge Crawler", "brightedgebot", "ADVERTISING_AND_MARKETING", NULL },
    { "channable/importer", "channable-importer", "ADVERTISING_AND_MARKETING", NULL },
    { "CitibotSiteCrawler", "citibotsitecrawler", "AI_CRAWLER", "ai-train" },
    { "FedReporterDataBot", "fedreporter-bot-for-ffiec-2", "AGGREGATOR", NULL },
    { "hey.com/imageproxy", "hey-email-privacy-proxy-2", "PAGE_PREVIEW", "search" },
    { "netarkivindsamling", "kb-dk-bot", "ACADEMIC_RESEARCH", "ai-train" },
    { "meta-externalagent", "meta-externalagent", "AI_CRAWLER", "ai-train" },
    { "polar\\.sh webhooks", "polar", "WEBHOOKS", NULL },
    { "SendGrid Event API", "sendgrid", "WEBHOOKS", NULL },
    { "ServerHunterSpider", "serverhunter", "OTHER", NULL },
    { "oslopartner Client", "stripe-apple-pay-verify-ownership", "WEBHOOKS", NULL },
    { "SwifteqLinkChecker", "swifteq-link-checker", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Yahoo Link Preview", "yahoolinkpreview", "PAGE_PREVIEW", "search" },
    { "SemanticScholarBot", "semantic-scholar-bot", "ACADEMIC_RESEARCH", "ai-train" },
    { "isitagentready.com", "cloudflare-agent-readiness", "MONITORING_AND_ANALYTICS", "monitor" },
    { "AppcastParsingBot", "appcastbot", "FEED_FETCHER", NULL },
    { "Better Uptime Bot", "better-uptime", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Chrome-Lighthouse", "chrome-lighthouse", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Cloudflare-Purge/", "cloudflare-purge", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "elmahio-uptimebot", "elmahio-uptimebot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "factset_spyderbot", "factset-spyderbot", "AI_CRAWLER", "ai-train" },
    { "Google-Read-Aloud", "googlereadaloud", "ACCESSIBILITY", "monitor" },
    { "MicrosoftPreview/", "microsoftpreview", "PAGE_PREVIEW", "search" },
    { "ModularConnector/", "modular-ds", "WEBHOOKS", NULL },
    { "montastic-monitor", "montasticmonitor", "MONITORING_AND_ANALYTICS", "monitor" },
    { "online-webceo-bot", "online-webceo-bot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Orlo-LinkPreview/", "orlo-link-preview", "PAGE_PREVIEW", "search" },
    { "cf-qualys-scanner", "pci-qualys", "SECURITY", NULL },
    { "PrintFriendly.com", "printfriendly", "WEBHOOKS", NULL },
    { "page-preview-tool", "salesviewer", "ADVERTISING_AND_MARKETING", NULL },
    { "https://sentry.io", "sentry", "SECURITY", NULL },
    { "Splunk Synthetics", "splunk-synthetics", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Wordfence Central", "wordfence-central", "SECURITY", NULL },
    { "umich.edu (Linux)", "umich-eecs498", "ACADEMIC_RESEARCH", "ai-train" },
    { "ScaleUpXQ-Crawler", "scaleupxq", "OTHER", NULL },
    { "AccessibleWebBot", "accessible-web-bot", "ACCESSIBILITY", "monitor" },
    { "BigScootsMonitor", "bigscootsmonitor", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Criticalcss.com/", "criticalcssbot", "OTHER", NULL },
    { "DigiCert DCV Bot", "digicert-dcv", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "GoogleImageProxy", "googleimageproxy", "PAGE_PREVIEW", "search" },
    { "GrapeshotCrawler", "grapeshot", "ADVERTISING_AND_MARKETING", NULL },
    { "www.getuptime.co", "jagged-pixel-uptime", "MONITORING_AND_ANALYTICS", "monitor" },
    { "KargoBot-Artemis", "kargobot-artemis", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Level9SearchBot/", "level-9-search-bot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "rogerbot-crawler", "rogerbot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Skroutz ImageBot", "skroutzimagebot", "OTHER", NULL },
    { "StatistikAustria", "statistikaustria", "OTHER", NULL },
    { "TheSkinnyCrawler", "theskinnyai", "AI_ASSISTANT", "ai-input" },
    { "Trellis-Services", "trellis-services", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "UptimeMonitoring", "uptime-monitoring", "MONITORING_AND_ANALYTICS", "monitor" },
    { "YahooCacheSystem", "yahoocache", "PAGE_PREVIEW", "search" },
    { "Claude-SearchBot", "claude-searchbot", "AI_SEARCH", "ai-input" },
    { "python-requests/", "python-requests", "LIBRARY_OR_TOOL", NULL },
    { "Sogou web spider", "sogou", "SEARCH_ENGINE_CRAWLER", "search" },
    { "AhrefsSiteAudit", "ahrefssiteaudit", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Algolia Crawler", "algolia", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Arachnid Shield", "arachnid-shield-api", "SECURITY", NULL },
    { "archive.org_bot", "archive-org-bot", "ARCHIVER", "search" },
    { "Audisto Crawler", "audisto-crawler", "MONITORING_AND_ANALYTICS", "monitor" },
    { "cloudflare-csup", "cloudflarecsup", "OTHER", NULL },
    { "weipay-webhooks", "coinbase", "WEBHOOKS", NULL },
    { "deadlinkchecker", "deadlinkchecker", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Mediatoolkitbot", "determ", "AGGREGATOR", NULL },
    { "eRepublik.tools", "eRepublik-tools", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Ghost Inspector", "ghost-inspector", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Google-Firebase", "google-firebase-bot", "ADVERTISING_AND_MARKETING", NULL },
    { "Googlebot-Image", "googlebotimages", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Googlebot-Video", "googlebotvideos", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Haiku-SearchBot", "haiku-searchbot", "AI_ASSISTANT", "ai-input" },
    { "hstspreload-bot", "hstspreload-bot", "OTHER", NULL },
    { "HubSpot Crawler", "hubspot-crawler", "OTHER", NULL },
    { "kakaotalk-scrap", "kakaotalk-scrap-2", "PAGE_PREVIEW", "search" },
    { "linkchecker.pro", "linkcheckerpro", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "LinksIndexerBot", "linksindexerbot", "PAGE_PREVIEW", "search" },
    { "Make/production", "make-platform", "WEBHOOKS", NULL },
    { "MissinglettrBot", "missinglettrbot", "ADVERTISING_AND_MARKETING", NULL },
    { "NIXStatsbot/1.1", "nixstats", "MONITORING_AND_ANALYTICS", "monitor" },
    { "NostoCrawlerBot", "nostocrawlerbot", "ADVERTISING_AND_MARKETING", NULL },
    { "www.oncrawl.com", "oncrawl", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "AdpResearchBot/", "payroll-bot", "AI_CRAWLER", "ai-train" },
    { "SearchAtlas Bot", "searchatlas-bot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "SecurityHeaders", "securityheaders", "SECURITY", NULL },
    { "SemrushBot-SWA/", "semrush-swa", "AI_CRAWLER", "ai-train" },
    { "SemrushBot-OCOB", "semrushbot-ocob", "AI_CRAWLER", "ai-train" },
    { "SentryUptimeBot", "sentry-uptime-monitoring", "MONITORING_AND_ANALYTICS", "monitor" },
    { "SkypeUriPreview", "skypeuripreview", "PAGE_PREVIEW", "search" },
    { "TwinWaveScanner", "splunk-attack-analyzer", "SECURITY", NULL },
    { "Storebot-Google", "storebot-google", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "curl/7.58.0-DEV", "thousand-eyes", "MONITORING_AND_ANALYTICS", "monitor" },
    { "www.uptimia.com", "uptimia", "MONITORING_AND_ANALYTICS", "monitor" },
    { "ygs-scraper-bot", "ygs-group-falconer-scraper", "AI_CRAWLER", "ai-train" },
    { "Zendesk Webhook", "zendesk-webhook", "WEBHOOKS", NULL },
    { "ClueWeb-Crawler", "clueweb-crawler", "ACADEMIC_RESEARCH", "ai-train" },
    { "FAST-WebCrawler", "fast-webcrawler", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Perplexity-User", "perplexity-user", "AI_ASSISTANT", "ai-input" },
    { "Go-http-client/", "go-http-client", "LIBRARY_OR_TOOL", NULL },
    { "FriendlyCrawler", "friendlycrawler", "OTHER", NULL },
    { "AgencyToolsPro", "agencytoolspro-uptime-monitoring-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "AmazonBuyForMe", "amazon-buyforme", "AI_ASSISTANT", "ai-input" },
    { "Anchor Browser", "anchor-browser", "AI_CRAWLER", "ai-train" },
    { "Caliperbot/1.0", "caliperbot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "cookie-maestro", "cookiemaestro", "SECURITY", NULL },
    { "EpivozCrawler/", "epivoz-crawler", "AGGREGATOR", NULL },
    { "ExodusMovement", "exodus-movement", "WEBHOOKS", NULL },
    { "FlipboardProxy", "flipboard", "PAGE_PREVIEW", "search" },
    { "CloudVertexBot", "google-cloudvertexbot", "AI_CRAWLER", "ai-train" },
    { "GoogleProducer", "google-publisher-center", "FEED_FETCHER", NULL },
    { "google-xrawler", "google-xrawler", "SEARCH_ENGINE_CRAWLER", "search" },
    { "GroovinaAdsbot", "groovinads", "ADVERTISING_AND_MARKETING", NULL },
    { "GuestpostsBot/", "guestpostsbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Instapaper/4.0", "instapaper", "OTHER", NULL },
    { "jobswithgptcom", "jobswithgptcom-bot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Magnet.me-web/", "magnetmebot", "AGGREGATOR", NULL },
    { "magpie-crawler", "magpiecrawler", "AI_CRAWLER", "ai-train" },
    { "MistralAI-User", "mistralai-user", "AI_ASSISTANT", "ai-input" },
    { "Clearscopebot/", "mushilabs-clearscopebot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "pinterest.com/", "pinterest", "AGGREGATOR", NULL },
    { "PressEngineBot", "press-engine-bot", "PAGE_PREVIEW", "search" },
    { "ecurly Webhook", "recurly", "WEBHOOKS", NULL },
    { "RetroListeCOM/", "retrolistecom", "MONITORING_AND_ANALYTICS", "monitor" },
    { "reward-gateway", "reward-gateway", "SECURITY", NULL },
    { "Server Density", "serverdensity", "MONITORING_AND_ANALYTICS", "monitor" },
    { "SiteLockSpider", "sitelock", "SECURITY", NULL },
    { "Slack-ImgProxy", "slackbotimg", "PAGE_PREVIEW", "search" },
    { "trendictionbot", "trendictionbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Upstash-QStash", "upstash-qstash", "AI_ASSISTANT", "ai-input" },
    { "VirusTotalScan", "virustotalscan", "SECURITY", NULL },
    { "webspidermount", "web-spider-mount", "AGGREGATOR", NULL },
    { "YahooMailProxy", "yahoo-mail-proxy", "PAGE_PREVIEW", "search" },
    { "YahooMailProxy", "yahoomailproxy", "PAGE_PREVIEW", "search" },
    { "Amzn-SearchBot", "amzn-searchbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "HeadlessChrome", "headlesschrome", "OTHER", NULL },
    { "BrokenLinksBot", "brokenlinks-io", "MONITORING_AND_ANALYTICS", "monitor" },
    { "GenomeCrawlerd", "nokia-genome-crawler", "ACADEMIC_RESEARCH", "ai-train" },
    { "monitoring360", "360monitoring", "MONITORING_AND_ANALYTICS", "monitor" },
    { "amazon-kendra", "amazon-kendra", "OTHER", NULL },
    { "atlassian-bot", "atlassian-bot", "AI_CRAWLER", "ai-train" },
    { "CapitalOneBot", "capitalonebot", "AGGREGATOR", NULL },
    { "ContextualBot", "contextualbot", "ADVERTISING_AND_MARKETING", NULL },
    { "DataForSeoBot", "dataforseo-bot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "DuckAssistBot", "duckassistbot", "AI_ASSISTANT", "ai-input" },
    { "EvoUptimeBot/", "evo-uptime-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "FDL Stats Bot", "fdl-stats-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "4f.at/crawler", "foureff", "AI_ASSISTANT", "ai-input" },
    { "Google-Safety", "google-safety", "SECURITY", NULL },
    { "Googlebot-IA/", "google-scholar", "SEARCH_ENGINE_CRAWLER", "search" },
    { "AdsBot-Google", "googleads", "ADVERTISING_AND_MARKETING", NULL },
    { "inoreader.com", "innologica", "FEED_FETCHER", NULL },
    { "mediaboardbot", "mediaboardbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "MedialogiaBot", "medialogiabot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "OAI-SearchBot", "oai-searchbot", "AI_SEARCH", "ai-input" },
    { "OpenGraph.io/", "opengraphbot", "PAGE_PREVIEW", "search" },
    { "Pro-Sitemaps/", "pro-sitemaps", "ACCESSIBILITY", "monitor" },
    { "SemrushBot-BA", "semrush-ba", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "SemrushBot-SA", "semrush-sa", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "SemrushBot-SI", "semrush-si", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "SiteSearch360", "site-search-360", "SEARCH_ENGINE_CRAWLER", "search" },
    { "SmartologyBot", "smartologybot-2", "ADVERTISING_AND_MARKETING", NULL },
    { "SparkShipping", "spark-shipping", "WEBHOOKS", NULL },
    { "SpyglassesBot", "spyglasses-bot", "AI_ASSISTANT", "ai-input" },
    { "StatsDroneBot", "statsdronebot", "AGGREGATOR", NULL },
    { "W3C-checklink", "w3-validator-services", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Y!J-BRU/VSIDX", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "YokoyGroupAG/", "yokoy-group", "WEBHOOKS", NULL },
    { "xAI-SearchBot", "xai-searchbot", "AI_SEARCH", "ai-input" },
    { "PerplexityBot", "perplexitybot", "AI_SEARCH", "ai-input" },
    { "CensysInspect", "censys", "SECURITY", NULL },
    { "python-httpx/", "python-httpx", "LIBRARY_OR_TOOL", NULL },
    { "AccessStatus", "accessstatus", "MONITORING_AND_ANALYTICS", "monitor" },
    { "ActiveComply", "activecomply-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "AddSearchBot", "addsearchbot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Advailo Kuma", "advailo-kuma", "MONITORING_AND_ANALYTICS", "monitor" },
    { "BigUpDataBot", "bigupdatabot", "ADVERTISING_AND_MARKETING", NULL },
    { "Digicert DCV", "cf-digicert-dcv", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "ChatGPT-User", "chatgpt-user", "AI_ASSISTANT", "ai-input" },
    { "Cloudtrellis", "cloudtrellis", "MONITORING_AND_ANALYTICS", "monitor" },
    { "consentcheck", "consentcheck", "OTHER", NULL },
    { "CookieYesbot", "cookieyesbot", "SECURITY", NULL },
    { "cron-job.org", "cronjob", "WEBHOOKS", NULL },
    { "RSiteAuditor", "dataforseo-siteauditor", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Dataprovider", "dataprovider-com", "SEARCH_ENGINE_CRAWLER", "search" },
    { "FlipboardRSS", "flipboardrss", "FEED_FETCHER", NULL },
    { "FullStoryBot", "fullstorybot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Google-Agent", "google-agent", "AI_ASSISTANT", "ai-input" },
    { "Hype Machine", "hypemachine", "SEARCH_ENGINE_CRAWLER", "search" },
    { "ICC-Crawler/", "icccrawler", "AI_CRAWLER", "ai-train" },
    { "IndeedJobBot", "indeedjobbot", "AGGREGATOR", NULL },
    { "LegalMonster", "legalmonster", "SECURITY", NULL },
    { "Macrobondbot", "macrobondbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "MotoMinerBot", "motominerbot", "AGGREGATOR", NULL },
    { "muckrack.com", "muck-rack-scraper", "FEED_FETCHER", NULL },
    { "PRTGCloudBot", "paesslermonitoring", "MONITORING_AND_ANALYTICS", "monitor" },
    { "pingping.io/", "pingping", "MONITORING_AND_ANALYTICS", "monitor" },
    { "pingping.io/", "pingpingbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "pulsetic.com", "pulsetic-8", "MONITORING_AND_ANALYTICS", "monitor" },
    { "QualifiedBot", "qualifiedbot", "AI_CRAWLER", "ai-train" },
    { "Quantcastbot", "quantcastbot", "ADVERTISING_AND_MARKETING", NULL },
    { "SFDC-Callout", "salesforce", "ADVERTISING_AND_MARKETING", NULL },
    { "SiteAuditBot", "semrush-siteauditbot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "seo4ajax.com", "seo4ajax", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "SeobilityBot", "seobilitybot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Slackbot 1.0", "slackbot", "WEBHOOKS", NULL },
    { "SMTnetPMBot/", "smtnetpmbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Snipcart/1.0", "snipcart", "WEBHOOKS", NULL },
    { "sender-9YMgn", "svix-webhooks", "WEBHOOKS", NULL },
    { "TwilioProxy/", "twilioproxy", "WEBHOOKS", NULL },
    { "Webstatus247", "webstatus247", "MONITORING_AND_ANALYTICS", "monitor" },
    { "WordCountBot", "wordcountbot", "PAGE_PREVIEW", "search" },
    { "Indy Library", "wordline", "WEBHOOKS", NULL },
    { "umbrella bot", "wp-umbrella-bot", "WEBHOOKS", NULL },
    { "Y!J-B|YJ-SAD", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "Y!J-MMP/dscv", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "Yahoo! Slurp", "yahooslurp", "SEARCH_ENGINE_CRAWLER", "search" },
    { "MegaIndex.ru", "megaindex", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "TikTokSpider", "tiktokspider", "AI_CRAWLER", "ai-train" },
    { "WellKnownBot", "well-known-dev", "MONITORING_AND_ANALYTICS", "monitor" },
    { "AliyunSecBot", "aliyun-secbot", "SECURITY", NULL },
    { "ImagesiftBot", "imagesiftbot", "OTHER", NULL },
    { "AmazonAdBot", "amazonadbot", "ADVERTISING_AND_MARKETING", NULL },
    { "A360-Search", "area-360", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Barkrowler/", "babbar-barkrowler", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Baiduspider", "baidu", "SEARCH_ENGINE_CRAWLER", "search" },
    { "BingPreview", "bingpreview", "PAGE_PREVIEW", "search" },
    { "channel3bot", "channel3bot", "AGGREGATOR", NULL },
    { "Collapsify/", "cloudflare-collapsify", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "contentking", "contentking", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Discordbot/", "discord-bot", "PAGE_PREVIEW", "search" },
    { "DuckDuckBot", "duckduckbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "GoogleOther", "google-other", "AI_CRAWLER", "ai-train" },
    { "APIs-Google", "googleapi", "WEBHOOKS", NULL },
    { "HetrixTools", "hetrixtools", "MONITORING_AND_ANALYTICS", "monitor" },
    { "HostTracker", "hosttracker", "MONITORING_AND_ANALYTICS", "monitor" },
    { "ias_crawler", "ias-crawler", "ADVERTISING_AND_MARKETING", NULL },
    { "Klaviyo/1.0", "klaviyo", "ADVERTISING_AND_MARKETING", NULL },
    { "Known Agent", "known-agent", "AI_ASSISTANT", "ai-input" },
    { "LinkedInBot", "linkedin", "PAGE_PREVIEW", "search" },
    { "Mail.RU_Bot", "mail-ru-bot", "PAGE_PREVIEW", "search" },
    { "NewRelicbot", "newrelic", "MONITORING_AND_ANALYTICS", "monitor" },
    { "OnlineOrNot", "onlineornot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "parsely.com", "parsely", "MONITORING_AND_ANALYTICS", "monitor" },
    { "SeekportBot", "seekport", "SEARCH_ENGINE_CRAWLER", "search" },
    { "SemrushBot/", "semrush-bl", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "SemrushBot;", "semrush-lb", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "serpstatbot", "serpstatbot-6", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "TelegramBot", "telegrambot", "PAGE_PREVIEW", "search" },
    { "TTD-Content", "ttd-content", "ADVERTISING_AND_MARKETING", NULL },
    { "Twitterbot/", "twitterbot", "PAGE_PREVIEW", "search" },
    { "UptimeBot/1", "uptimebot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "UptimeRobot", "uptimerobot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "videootvBot", "videootvbot", "AGGREGATOR", NULL },
    { "WovnCrawler", "wovn-crawler-3", "ACCESSIBILITY", "monitor" },
    { "ZoominfoBot", "zoominfobot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "DeepSeekBot", "deepseekbot", "AI_CRAWLER", "ai-train" },
    { "BitSightBot", "bitsight", "SECURITY", NULL },
    { "Linguee Bot", "linguee", "OTHER", NULL },
    { "FinepdfsBot", "huggingface-finepdfs", "AI_CRAWLER", "ai-train" },
    { "GuzzleHttp/", "guzzlehttp", "LIBRARY_OR_TOOL", NULL },
    { "Monsidobot", "acquia-optimize-monsido", "MONITORING_AND_ANALYTICS", "monitor" },
    { "BestChange", "bestchange-bot", "AGGREGATOR", NULL },
    { "bnf.fr_bot", "bibliotheque-nacional-de-france", "ACADEMIC_RESEARCH", "ai-train" },
    { "Blogtrottr", "blogtrottr", "FEED_FETCHER", NULL },
    { "BlogVault/", "blogvault", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Buttondown", "buttondown-rss-feed-parser", "FEED_FETCHER", NULL },
    { "Catchpoint", "catchpoint", "MONITORING_AND_ANALYTICS", "monitor" },
    { "CertChief/", "cert-chief", "SECURITY", NULL },
    { "CledaraBot", "cledara-saas-management-agent", "AI_ASSISTANT", "ai-input" },
    { "Convermax/", "convermaxbot", "FEED_FETCHER", NULL },
    { "CriteoBot/", "criteobot", "ADVERTISING_AND_MARKETING", NULL },
    { "cXensebot/", "cxensebot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "eMoneyBot/", "emoneybot", "AGGREGATOR", NULL },
    { "FastmailUA", "fastmail-bot", "PAGE_PREVIEW", "search" },
    { "Flashy-PHP", "flashy-php-1-0-0", "WEBHOOKS", NULL },
    { "Funnelback", "funnelback", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Googlebot/", "google", "SEARCH_ENGINE_CRAWLER", "search" },
    { "idealo-bot", "idealo-2", "AGGREGATOR", NULL },
    { "Instapaper", "instapaper", "OTHER", NULL },
    { "Integromat", "integromatbot", "WEBHOOKS", NULL },
    { "Archive-It", "internet-archive-archive-it", "ARCHIVER", "search" },
    { "kinsta-bot", "kinsta-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "line-poker", "line-ogp-scraper", "SOCIAL_MEDIA_MARKETING", NULL },
    { "Linespider", "linespider", "SEARCH_ENGINE_CRAWLER", "search" },
    { "CentComBot", "melonmesabot", "OTHER", NULL },
    { "MonitoRSS/", "monitorss", "FEED_FETCHER", NULL },
    { "ohdear.app", "ohdear", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Verispider", "project-honeypot", "SECURITY", NULL },
    { "Reelevant/", "reelevant", "ADVERTISING_AND_MARKETING", NULL },
    { "RevvimGort", "revvim", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "rss2tg bot", "rss2tg-bot", "FEED_FETCHER", NULL },
    { "SiteUptime", "siteuptime", "MONITORING_AND_ANALYTICS", "monitor" },
    { "SkroutzBot", "skroutzbot", "FEED_FETCHER", NULL },
    { "slopsearch", "slopsearch", "AI_ASSISTANT", "ai-input" },
    { "solarwinds", "solarwinds-observability", "MONITORING_AND_ANALYTICS", "monitor" },
    { "statuscake", "statuscake", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Stripe/1.0", "stripe", "WEBHOOKS", NULL },
    { "Taboolabot", "taboola", "ADVERTISING_AND_MARKETING", NULL },
    { "Terracotta", "terracotta", "SEARCH_ENGINE_CRAWLER", "search" },
    { "VaultPress", "vaultpress", "WEBHOOKS", NULL },
    { "WebsiteOps", "watchful", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Citoid/WMF", "wikimedia-citoid", "OTHER", NULL },
    { "WordPress/", "wordpress-namecheap", "OTHER", NULL },
    { "WPUmbrella", "wp-umbrella", "MONITORING_AND_ANALYTICS", "monitor" },
    { "ZipchatBot", "zipchatbot", "AI_ASSISTANT", "ai-input" },
    { "MistralBot", "mistralbot", "AI_CRAWLER", "ai-train" },
    { "Bytespider", "bytespider", "AI_CRAWLER", "ai-train" },
    { "leakix.net", "leakix", "SECURITY", NULL },
    { "Centurybot", "centurybot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "2checkout", "2checkout", "WEBHOOKS", NULL },
    { "AASA-Bot/", "aasa", "OTHER", NULL },
    { "Adagiobot", "adagiobot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "AhrefsBot", "ahrefsbot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "AlertSite", "alertsite", "MONITORING_AND_ANALYTICS", "monitor" },
    { "AllAfrica", "allafrica-crawler", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Amazonbot", "amazon-bot", "AI_CRAWLER", "ai-train" },
    { "Baidu-ADS", "baidu-ads", "SEARCH_ENGINE_CRAWLER", "search" },
    { "bigsur.ai", "big-sur-ai", "AI_CRAWLER", "ai-train" },
    { "BuiltWith", "builtwith", "MONITORING_AND_ANALYTICS", "monitor" },
    { "bushbaby/", "bushbaby", "SECURITY", NULL },
    { "ChargeBee", "chargebee", "WEBHOOKS", NULL },
    { "CheckView", "checkview-24", "MONITORING_AND_ANALYTICS", "monitor" },
    { "cludo.com", "cludobot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "coccocbot", "coccocbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "James BOT", "cognitiveseo", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "CookieHub", "cookie-hub", "SECURITY", NULL },
    { "Cookiebot", "cookiebot", "SECURITY", NULL },
    { "Cotoyogi/", "cotoyogi", "AI_CRAWLER", "ai-train" },
    { "Crawlson/", "crawlson", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Crazy Egg", "crazy-egg-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "DeckAgent", "deck-agent", "AI_ASSISTANT", "ai-input" },
    { "DMBrowser", "dotcom-monitor", "MONITORING_AND_ANALYTICS", "monitor" },
    { "EasyCron/", "easycron", "WEBHOOKS", NULL },
    { "feeder.co", "feeder", "FEED_FETCHER", NULL },
    { "FeedOtter", "feedotter", "FEED_FETCHER", NULL },
    { "Feedwind/", "feedwind", "FEED_FETCHER", NULL },
    { "follow.it", "fit-feeds-fetcher", "FEED_FETCHER", NULL },
    { "Foregenix", "foregenix-threatview-webscan", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Freshping", "freshping", "ACCESSIBILITY", "monitor" },
    { "Huckabot/", "huckabot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "IsDownBot", "isdownbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "LinkTiger", "linktiger", "MONITORING_AND_ANALYTICS", "monitor" },
    { "LoomlyBot", "loomlybot", "PAGE_PREVIEW", "search" },
    { "MarketGoo", "marketgoo", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Mavifinds", "mavifinds-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "mirrorweb", "mirrorwebcrawler", "AGGREGATOR", NULL },
    { "MojeekBot", "mojeekbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "MonSpark/", "mon-spark", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Prerender", "prerender", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Protopage", "protopage", "FEED_FETCHER", NULL },
    { "Readable/", "readable", "ACCESSIBILITY", "monitor" },
    { "scour.ing", "scour-rss-bot", "FEED_FETCHER", NULL },
    { "SeznamBot", "seznam", "SEARCH_ENGINE_CRAWLER", "search" },
    { "SmarshBot", "smarsh", "SECURITY", NULL },
    { "SparkPost", "sparkpost", "WEBHOOKS", NULL },
    { "SteamChat", "steam-chat", "PAGE_PREVIEW", "search" },
    { "Stripebot", "stripebot", "WEBHOOKS", NULL },
    { "TermlyBot", "termly", "OTHER", NULL },
    { "TermlyBot", "termlybot-2", "MONITORING_AND_ANALYTICS", "monitor" },
    { "TwinAgent", "twinagent", "AI_ASSISTANT", "ai-input" },
    { "updown.io", "updown", "MONITORING_AND_ANALYTICS", "monitor" },
    { "WJHRO/1.0", "worldpay", "WEBHOOKS", NULL },
    { "WormlyBot", "wormly", "MONITORING_AND_ANALYTICS", "monitor" },
    { "ClaudeBot", "claudebot", "AI_CRAWLER", "ai-train" },
    { "CohereBot", "coherebot", "AI_CRAWLER", "ai-train" },
    { "LinkupBot", "linkup", "AI_SEARCH", "ai-input" },
    { "l9explore", "leakix", "SECURITY", NULL },
    { "UrlBeeBot", "urlbee", "MONITORING_AND_ANALYTICS", "monitor" },
    { "adidxbot", "adidxbot", "ADVERTISING_AND_MARKETING", NULL },
    { "contxbot", "amazon-contxtbot", "ADVERTISING_AND_MARKETING", NULL },
    { "Applebot", "apple", "AI_SEARCH", "ai-input" },
    { "ArenaBot", "arena-bot", "PAGE_PREVIEW", "search" },
    { "Attracta", "attracta", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Authory/", "authory", "OTHER", NULL },
    { "bingbot/", "bing", "SEARCH_ENGINE_CRAWLER", "search" },
    { "FastDAST", "black-duck-fast-dynamic", "SECURITY", NULL },
    { "BlingERP", "bling-erp", "OTHER", NULL },
    { "Bluesky/", "bluesky-app", "PAGE_PREVIEW", "search" },
    { "Bravebot", "bravebot", "AI_SEARCH", "ai-input" },
    { "Coveobot", "coveobot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "CybaaBot", "cybaa-bot", "SECURITY", NULL },
    { "Daum/4.1", "daum", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Leikibot", "doubleverify", "ADVERTISING_AND_MARKETING", NULL },
    { "Dratabot", "drata", "SECURITY", NULL },
    { "EasyScan", "easyscan", "AI_ASSISTANT", "ai-input" },
    { "Feedly/1", "feedly", "FEED_FETCHER", NULL },
    { "FullFact", "fullfact-ingest", "FEED_FETCHER", NULL },
    { "GTmetrix", "gtmetrix", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Kagibot/", "kagi", "SEARCH_ENGINE_CRAWLER", "search" },
    { "LinerBot", "liner-bot", "AI_CRAWLER", "ai-train" },
    { "ManageWP", "managewp", "WEBHOOKS", NULL },
    { "Monitage", "monitage", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Neevabot", "neevabot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Netcraft", "netcraft", "SECURITY", NULL },
    { "NETVIGIE", "netvigie", "MONITORING_AND_ANALYTICS", "monitor" },
    { "NewsBlur", "news-blur", "FEED_FETCHER", NULL },
    { "NewsBank", "newsbank", "ARCHIVER", "search" },
    { "NodePing", "nodeping", "MONITORING_AND_ANALYTICS", "monitor" },
    { "noorobot", "noorobot", "ADVERTISING_AND_MARKETING", NULL },
    { "Novellum", "novellum-ai-crawl", "AI_CRAWLER", "ai-train" },
    { "Omnisend", "omnisend", "WEBHOOKS", NULL },
    { "OneTrust", "onetrust-cmp-scanner", "MONITORING_AND_ANALYTICS", "monitor" },
    { "outbrain", "outbrain", "ADVERTISING_AND_MARKETING", NULL },
    { "OdklBot/", "ozon-web-grabber", "PAGE_PREVIEW", "search" },
    { "PetalBot", "petalbot", "AI_CRAWLER", "ai-train" },
    { "Potions/", "potions", "SEARCH_ENGINE_CRAWLER", "search" },
    { "SSL Labs", "qualys", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Qwantbot", "qwantbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Razorpay", "razorpay-webhook-3", "WEBHOOKS", NULL },
    { "Robinbot", "robinbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "ScavoBot", "scavobot", "AI_ASSISTANT", "ai-input" },
    { "SEBot-WA", "se-ranking-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "SequelWP", "sequelwpbpt", "MONITORING_AND_ANALYTICS", "monitor" },
    { "ShapBot/", "sharpbot", "AI_CRAWLER", "ai-train" },
    { "Silktide", "silktidebot", "ACCESSIBILITY", "monitor" },
    { "site24x7", "site24x7", "MONITORING_AND_ANALYTICS", "monitor" },
    { "SlickBot", "slickstream", "ADVERTISING_AND_MARKETING", NULL },
    { "Sora POS", "sora-caisse-pos", "OTHER", NULL },
    { "Spectate", "spectate", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Statabot", "statabot", "AGGREGATOR", NULL },
    { "Trustly/", "trustly", "WEBHOOKS", NULL },
    { "Turnitin", "turnitinbot", "ACADEMIC_RESEARCH", "ai-train" },
    { "uptrends", "uptrends", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Watchbot", "watchbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "wknd-bot", "wkndhealthcheckbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "bitlybot", "bitlybot", "PAGE_PREVIEW", "search" },
    { "ThinkBot", "thinkbot", "OTHER", NULL },
    { "SEOkicks", "seokicks", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "WadooBot", "wadoo", "OTHER", NULL },
    { "Timpibot", "timpibot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "aiHitBot", "aihitbot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "AddThis", "addthis", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Akismet", "akismet", "WEBHOOKS", NULL },
    { "Tumblr/", "automattic-tumblr", "PAGE_PREVIEW", "search" },
    { "BLEXBot", "blexbot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "BugsNag", "bugsnag", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Checkly", "checkly", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Datadog", "datadog-synthetic-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Anomura", "direqt-anomura", "AI_SEARCH", "ai-input" },
    { "Feedbin", "feedbin", "FEED_FETCHER", NULL },
    { "FishBot", "fishbot", "AI_CRAWLER", "ai-train" },
    { "FlockWP", "flockwp", "AI_ASSISTANT", "ai-input" },
    { "Gigabot", "gigabot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Notabot", "helpfeel-notabot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "HIFIBot", "hifibot", "OTHER", NULL },
    { "IbouBot", "iboubot-3", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Innguma", "innguma-fetcher", "FEED_FETCHER", NULL },
    { "MagiBot", "magibot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "MainWP/", "mainwp", "WEBHOOKS", NULL },
    { "Metorik", "metorik", "WEBHOOKS", NULL },
    { "MgidBot", "mgidbot", "ADVERTISING_AND_MARKETING", NULL },
    { "MJ12bot", "mj12bot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "monitis", "monitis", "MONITORING_AND_ANALYTICS", "monitor" },
    { "MRGbot/", "mrgbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "msnbot/", "msnbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "NewsNow", "newsnow", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Nooshub", "nooshub", "FEED_FETCHER", NULL },
    { "OpenRSS", "openrss", "FEED_FETCHER", NULL },
    { "Panopta", "panopta", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Retool/", "retool", "OTHER", NULL },
    { "RSSAPI/", "rssapi", "FEED_FETCHER", NULL },
    { "Uptime/", "uptime", "MONITORING_AND_ANALYTICS", "monitor" },
    { "WARDBot", "wardbot", "AI_CRAWLER", "ai-train" },
    { "WPMUDEV", "wpmudev-uptime-monitor-5-0", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Y!J-ASR", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "Y!J-BRW", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "Y!J-WSC", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "YextBot", "yextbot", "ADVERTISING_AND_MARKETING", NULL },
    { "Scrapy/", "scrapy", "LIBRARY_OR_TOOL", NULL },
    { "ELinks/", "elinks", "OTHER", NULL },
    { "EECS498", "umich-eecs498", "ACADEMIC_RESEARCH", "ai-train" },
    { "okhttp/", "okhttp", "LIBRARY_OR_TOOL", NULL },
    { "HaloBot", "halobot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "aa/1.0", "agency-analytics-crawler", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Awario", "awario", "AI_CRAWLER", "ai-train" },
    { "BazQux", "bazqux", "FEED_FETCHER", NULL },
    { "botify", "botify", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "curly-", "cloudflare-observatory-curly", "MONITORING_AND_ANALYTICS", "monitor" },
    { "DotBot", "dotbot", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Fedica", "fedicaapp", "SOCIAL_MEDIA_MARKETING", NULL },
    { "GPTBot", "gptbot", "AI_CRAWLER", "ai-train" },
    { "Hatena", "hatena", "FEED_FETCHER", NULL },
    { "Hotjar", "hotjar", "MONITORING_AND_ANALYTICS", "monitor" },
    { "IABot/", "internet-archive-bot", "MONITORING_AND_ANALYTICS", "monitor" },
    { "jetmon", "jetpack", "MONITORING_AND_ANALYTICS", "monitor" },
    { "(dbot)", "mars-finder", "SEARCH_ENGINE_CRAWLER", "search" },
    { "netumo", "netumo", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Nitro-", "nitro", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "Paddle", "paddle-webhooks", "WEBHOOKS", NULL },
    { "PayPal", "paypal", "WEBHOOKS", NULL },
    { "Sucuri", "sucuri", "SECURITY", NULL },
    { "upday/", "upday", "AGGREGATOR", NULL },
    { "WTotem", "webtotem", "SECURITY", NULL },
    { "YJ-SAD", "yahoo-japan", "ADVERTISING_AND_MARKETING", NULL },
    { "J-BRW/", "yahoo-jp-seo", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "J-DLC/", "yahoojapan", "SEARCH_ENGINE_CRAWLER", "search" },
    { "YouBot", "youbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Zapier", "zapier", "WEBHOOKS", NULL },
    { "ZumBot", "zumbot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Exabot", "exabot", "SEARCH_ENGINE_CRAWLER", "search" },
    { "PycURL", "pycurl", "LIBRARY_OR_TOOL", NULL },
    { "l9scan", "leakix", "SECURITY", NULL },
    { "zgrab/", "zgrab", "SECURITY", NULL },
    { "Adyen", "adyen", "WEBHOOKS", NULL },
    { "lumar", "deepcrawl", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Devin", "devin", "AI_ASSISTANT", "ai-input" },
    { "Gatus", "gatus", "MONITORING_AND_ANALYTICS", "monitor" },
    { "GoPay", "gopay", "WEBHOOKS", NULL },
    { "IFTTT", "ifttt-rss-feed-service", "FEED_FETCHER", NULL },
    { "Jumio", "jumio", "SECURITY", NULL },
    { "Nava/", "nava-labs-asp-dev", "AI_ASSISTANT", "ai-input" },
    { "Yeti/", "naver", "SEARCH_ENGINE_CRAWLER", "search" },
    { "Noibu", "noibu", "ACCESSIBILITY", "monitor" },
    { "Rigor", "rigor", "MONITORING_AND_ANALYTICS", "monitor" },
    { "Stape", "stape-scanner", "MONITORING_AND_ANALYTICS", "monitor" },
    { "J-BRW", "yahoo-jp-seo", "SEARCH_ENGINE_OPTIMIZATION", "search" },
    { "CCBot", "ccbot", "ARCHIVER", "search" },
    { "tcpdf", "tcpdf", "LIBRARY_OR_TOOL", NULL },
    { "curl/", "curl", "LIBRARY_OR_TOOL", NULL },
    { "Wget/", "wget", "LIBRARY_OR_TOOL", NULL },
    { "Dlc/", "drlinkcheck", "MONITORING_AND_ANALYTICS", "monitor" },
    { NULL, NULL, NULL, NULL }
};

const apr_size_t bs_known_bots_count = 631;
